input.onButtonPressed(Button.A, function () {
  basic.showNumber(7)
  basic.pause(100)
  basic.showNumber(3)
  basic.pause(100)
  basic.showNumber(1)
  basic.pause(100)
  basic.showNumber(8)
  basic.pause(100)
  basic.showNumber(0)
  basic.pause(100)
})
input.onGesture(Gesture.Shake, function () {
  let reiniciar = 0
  basic.showArrow(reiniciar)
})
input.onButtonPressed(Button.B, function () {
  let pressionar = 0
  basic.showNumber(3)
  basic.pause(pressionar)
  basic.showIcon(IconNames.Yes)
  basic.showNumber(0)
  basic.pause(pressionar)
  basic.showIcon(IconNames.Yes)
  basic.pause(pressionar)
  basic.showNumber(2)
  basic.pause(pressionar)
  basic.showNumber(4)
  basic.pause(pressionar)
  basic.showNumber(1)
  basic.pause(pressionar)
  basic.showIcon(IconNames.Yes)
  basic.showNumber(5)
  basic.pause(pressionar)
  basic.showNumber(8)
  basic.pause(pressionar)
  basic.showIcon(IconNames.Yes)
  basic.showNumber(9)
  basic.pause(pressionar)
  basic.showNumber(7)
  basic.pause(pressionar)
  basic.showIcon(IconNames.Yes)
})
basic.showString("Oi!")

